#!/bin/bash
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
export GOTOOLCHAIN=go1.26.8
export GOBIN="$root/.build/tailscale-tools"
mkdir -p "$GOBIN"
go install github.com/google/go-licenses/v2@v2.0.1
cd "$root/Tailscale"
notices="$root/.build/tailscale-notices"
if [ -d "$notices" ]; then rm -rf "$notices"; fi
"$GOBIN/go-licenses" save . --ignore bitdream.local/tailscale --save_path "$notices/macos"
GOOS=ios GOARCH=arm64 CGO_ENABLED=1 CC="$(xcrun --find clang)" \
    CGO_CFLAGS="-target arm64-apple-ios26.0 -isysroot $(xcrun --sdk iphoneos --show-sdk-path)" \
    "$GOBIN/go-licenses" save . --ignore bitdream.local/tailscale --save_path "$notices/ios"
cp "$(go env GOROOT)/LICENSE" "$notices/Go-LICENSE"
python3 - "$root" "$notices" <<'PY'
from pathlib import Path
import sys
root, directory = map(Path, sys.argv[1:])
entries = {}
for platform in ('macos', 'ios'):
    for path in sorted((directory/platform).rglob('*')):
        if path.is_file():
            entries[str(path.relative_to(directory/platform))] = path.read_text()
entries['Go/LICENSE'] = (directory/'Go-LICENSE').read_text()
text = 'Tailscale and dependency notices\nGenerated by scripts/update-tailscale-notices.sh.\n\n'
for name, license_text in sorted(entries.items()):
    text += name + '\n' + '=' * len(name) + '\n' + license_text.rstrip() + '\n\n'
output = root/'BitDream/Resources/TailscaleNotices.txt'
output.parent.mkdir(parents=True, exist_ok=True)
output.write_text(text.rstrip()+'\n')
PY
